services:
  shorten:
    image: epochml/link-shortener:latest
    restart: on-failure
    environment:
      - DB_VENDOR=sqlite
      - DB_FILE=/data/db.sqlite3
      - SESSION_DB_FILE_LOC=/data/
      - SESSION_DB_FILE_NAME=sessions.sqlite3
      - CLIENT_SECRET
    ports:
      - "9215:9215"
    volumes:
      - ${PWD}/db.sqlite3:/data/db.sqlite3
      - ${PWD}/sessions.sqlite3:/data/sessions.sqlite3
